* Introductory stuff, Detectros and Particle physics
In this talk I will present you a study of multi variate and signle variate methods in the searches of resonant signatures at the LHC
** Coordinates at the CMS
I will firstly introduce the  coordinates used in the CMS. So, the 3 variables used, are the momenta of the particles in the transverse plane, that is a plane perpendicular to the beam axis, the aximuthal angle of the partilces, and finally the pseudorapidity of the particles, which is related to the polar angle angle of the particles.

We see here their relation to the cartesian coordinates. Z axis is parallel to the beam.
Lastly with the use of thses variables we can represent an event, that is a signle pp colission. So when I will be talking about events latter on, i will be refering to an array of Pts Etas and Phis and mabe some derivative variables, of all the particles of interest, produced in a colision.   
** Decays & Resonances
When protons collide, new partilces are beeing created. Usually they are unstable and decay in more stable partilces, like leptons, photons and quarks which we then detect, and the mass of the unstable parent particle. Practically this calculation results into a peak at the mass spectrum, which we call a resonance. A famous one is Z decaing to two leptons.

On the other hand, not every particle can be detected by the CMS detecor, and processes which contain such particles cannot result into a peak in the mass spectrum due to the missing momentum and energy of the undetected particle.

** Calibration and energy scale uncertainties
Why resonances are important?
An obvious answer is that they provide a way to probe and study the properties of the particles produced at the LHC.
More over we use resonances, callibrate the energy scale and resolution of the detector. How do we do that?
Basically we want the peaks of the J/psi and the Z boson to appear to the correct place, with the expected width in the mass spectrum.
Now, simulations are not perfect, the detector is not perfect and we end up with dissagrements in simulation and data that manifest as unsertainties in the energy scale in the analysis. 

This beggs the question how do analysis techniques respond to energy scale uncertainties? 
This is exactly what we are going study. Our work will investigate the effects of energy scale uncertainties, in searches for resonances. We will be using the generic diobject production as the working exmple, so some particle Y decays in two light X particles. and we will study how energy scale uncertainties affect the performance of a traditional fit based analysis and a more modern Machine Learning based analysis using boosted descision tree models.

* Method
** Searches for Y to XX 
We will present two searches. One heavy Y to XX where the mass of Y particle is 200GeV, and one lighter Y to xx with the mass of the Y particle beeing 60GeV.
** The Y to XX channel
So the first step to conduct the study is to prepare the data sets we are going to analyze.
For background we used the drell yan proces, and for signal we used the W phi to ll. Despite the fact that the final states we worked with were leptons, we treated them as generic x pairs. So the whole search is process agnositic.
Having the data set, we then proceed and separate signal from background by fitting the mass spectrum and by the use of  bdts. finally we apply energy scale uncertainties to the signal and we perform the separation again and compare the results. 
** Statistical interpretations of reults
 we will be assesing the perfomance of the two models, in terms of statistical significance as defined in poisson statistics, due to the poissonian nature of counting at the CMS detector,
* Search for light Y to ll
Now lets see all these in practice.
