#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:nil title:t toc:nil todo:nil |:t
#+title: Presentation draft
#+date:  
#+author: Konstantinos Papadimos
#+email: dinogreco2000@gmail.com
#+latex_header: \mode<beamer>{\usetheme{Madrid}}
#+latex_header: \mode<beamer>{\usepackage{amsmath}}
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.5.5)
#+cite_export:
#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [bigger]
#+OPTIONS: H:2
#+COLUMNS: %45ITEM %10BEAMER_env(Env) %10BEAMER_act(Act) %4BEAMER_col(Col) %8BEAMER_opt(Opt)

* Introductory stuff, Detectros and Particle physics
** The CMS Experiment overview
The CMS detector at the LHC
\begin{figure}[hb]
\centering
\includegraphics[width=0.7 \textwidth, ext=.png type=jpg]{/home/kpapad/UG_thesis/Thesis/Dissertation/src/figures/cms_detector.jpg}
\end{figure}

** Coordinates at the CMS
*** Text
:PROPERTIES:
    :BEAMER_env: ignoreheading
    :BEAMER_col: 0.33
    :END:
Given the solenoid geometry of the CMS detector, it is more convenient to use a spherical type of coordinates\( \left(r, \phi, \theta \right) \).
*** The coordinates
:PROPERTIES:
    :BEAMER_env: ignoreheading
    :BEAMER_col: 0.33
    :END:
\begin{equation}
\begin{matrix}
p_{x} = P_{T}\cos{\phi} \\
p_{y} = P_{T}\sin{\phi} \\
p_{z} = P_{T}\sinh{\eta}\\
|\vec{P}| = P_{T}\cosh{\eta} 
\end{matrix}
\end{equation}
*** Text
:PROPERTIES:
    :BEAMER_env: ignoreheading
    :BEAMER_col: 0.33
    :END:
\(\phi \in \left [ 0, 2\pi \right]\)the azimuthal angle, and \(\eta\in \left [ -\infty, +\infty \right ]\) is defined as:
\begin{equation}
\eta \equiv -\ln{\left [ \tan\left (\frac{\theta}{2} \right ) \right]  }
\end{equation}

** Decays & Resonances
Not every particle can be detected by the CMS detector(i.e neutrinos)
*** Resonance
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- Detectable Decay Products \(\rightarrow\) Resonance
#+ATTR_LaTeX: :width 0.8\textwidth
[[/home/kpapad/UG_thesis/Thesis/Analysis/out/Plots/DYJetsM50_MassHist.pdf]]

*** Not a resonance
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
#+ATTR_LaTeX: :width 0.8\textwidth
- Non Detectable Decay Products \(\rightarrow\) Not a resonance
[[/home/kpapad/UG_thesis/Thesis/Analysis/out/Plots/DYJetsM50_MassHist.pdf]]

** Calibration and energy scale uncertainties
  - Calibration process adjusts energy scale and resolution to match well-known resonances (Z boson, J/psi meson) in data and simulation,
 - Imperfect agreement due to subdetector complexities and nonlinear effects
*** How do analysis techniques respond to energy scale uncertainties ?
Our work will focus on the effects that energy scale uncertainties have, on a traditional fit-based analysis and a more modern Boosted Decision Tree-based analysis, using the generic diobject production process as the working example.
* Analysis techniqies
** BDT 1: Supervised Learning
*Supervised learning*:
 - The model is trained using training data
 - The trained model is tested using testing data
 - If we like the resulting model, we apply it!
   
*but what is this model?*
 - A function that given the input feautres x, it returns the probability x beeing class A
 - The goal of the training is to minimize the difference between the predicted output \(y_{i} \in [0, 1]\) and the real output \(\hat{y_{i}} = 0\text{ class B, or }\hat{y_{i}} = 1\text{ class A}\) 
** BDT 2a: Boosted decision trees
In this study the model of choice is Boosted Decision Trees(BDT).
 - It classifies data using decision tree models
\begin{figure}[h]
\centering
\includegraphics[width=0.85 \textwidth, ext=.png type=png]{/home/kpapad/UG_thesis/Thesis/Dissertation/Presentation/figures/cart.png}
\end{figure}
** BDT 2b: Boosted Decision Trees
Usually only one tree is not power full enough --> Use  more trees in additive manner(Boosting)
\begin{figure}[h]
\centering
\includegraphics[width=0.85 \textwidth, ext=.png type=png]{/home/kpapad/UG_thesis/Thesis/Dissertation/Presentation/figures/twocart.png}
\end{figure}
** BDT 3a: Signal from Background Separation
*In our case*:
- Signal: a resonant decay Y->xx
- Background: a non resonant process
*How to separate them?*
- Plot the number of Signal and Background events per BDT score --> BDT histogram
** BDT 3b: Signal from background separation
 Where should we place the cut in order to accpet most most of the  signal while rejecting most of background?
\begin{figure}[hb]
\centering
\includegraphics[page=2, width=0.85 \textwidth, ext=.png type=jpg]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M60M5080DeltasPConf12BDTplot.pdf}
\end{figure}
** Fit

** Statistical interpretation of results
Talk about significance.
* Analysis
** Energy scale uncertainties
How we implemented the smearing in our data set. How do we proceed from that, how many smearing cases. 
** BDT approach 1
Train Testing application set. Summarize the number of events. Explain that in order to compare apples to apples, we will be analyzing the application set from now on.
** BDT approach 2
Application summarize the results 
** Fit based approach 1
Show the mass spectrum that will be fitted 
** Fit based approach 2
discuss bkg fit is kept constnat throughout the analysis. discus signal fitting, show the plots( I will probably need more than one slide) at this part talk about the fact that after $20\%$ the fit based technique fails. 
** Fit based approach 2
Present the significances.
* Results
** Results 1
Compare the BDT and FIt in terms of significance and robustness. Comment that even though fit based achieves a higher significance in the 0 smearing case, it is not as robust as bdt, it completelly fails at extreme cases of smearing,. BDT is more robust 
** Results 2
Try to explain that bdt uses not only energy related features (Pts) but also geometrical ones, which do not get affected by smearing. Therefore, more stabillity to smearing. Nevertheless robustness does not mean greateer classification "power"(how many events got classified correctly and how manny didn't) -->Outlooks for better training methods in other to increase classification power.   
* Unused stuff
** Resonance text
and therefore, the invariant mass calculation from the detected particles of such events will not result in a peak at the mass spectrum(Non resonant proces). Even though in decays where  the poducts are detectable particles, the invariant mass calculation leads to a peak in the mass spectrum(resonant decays). In the present work we are interested in the later.

