#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:nil title:t toc:nil todo:nil |:t
#+title: Machine learning Techniques in the Searches for Resonant Signatures at the LHC 
#+date:  
#+author: Konstantinos Papadimos
#+email: dinogreco2000@gmail.com
#+latex_header: \mode<beamer>{\usetheme{boxes}}
#+latex_header: \mode<beamer>{\usepackage{amsmath}}
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.5.5)
#+cite_export:
#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [bigger]
#+OPTIONS: H:2
#+COLUMNS: %45ITEM %10BEAMER_env(Env) %10BEAMER_act(Act) %4BEAMER_col(Col) %8BEAMER_opt(Opt)

* Introductory stuff, Detectros and Particle physics
** Coordinates at the CMS
*** Text
:PROPERTIES:
    :BEAMER_env: ignoreheading
    :BEAMER_col: 0.33
    :END:
Given the solenoid geometry of the CMS detector, it is more convenient to use a spherical type of coordinates\( \left(r, \phi, \theta \right) \).
*** The coordinates
:PROPERTIES:
    :BEAMER_env: ignoreheading
    :BEAMER_col: 0.33
    :END:
\begin{equation}
\begin{matrix}
p_{x} = P_{T}\cos{\phi} \\
p_{y} = P_{T}\sin{\phi} \\
p_{z} = P_{T}\sinh{\eta}\\
|\vec{P}| = P_{T}\cosh{\eta} 
\end{matrix}
\end{equation}
*** Text
:PROPERTIES:
    :BEAMER_env: ignoreheading
    :BEAMER_col: 0.33
    :END:
\(\phi \in \left [ 0, 2\pi \right]\)the azimuthal angle, and \(\eta\in \left [ -\infty, +\infty \right ]\) is defined as:
\begin{equation}
\eta \equiv -\ln{\left [ \tan\left (\frac{\theta}{2} \right ) \right]  }
\end{equation}

** Decays & Resonances
Not every particle can be detected by the CMS detector(i.e neutrinos)
*** Resonance
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- Peak in the mass spectrum \(\rightarrow\) Resonance
#+ATTR_LaTeX: :width 0.8\textwidth
[[/home/kpapad/UG_thesis/Thesis/Analysis/out/Plots/DYJetsM50_MassHist.pdf]]

*** Not a resonance
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
#+ATTR_LaTeX: :width 0.8\textwidth
- Not a peak in the mass \(\rightarrow\) Not a resonance
[[/home/kpapad/UG_thesis/Thesis/Analysis/out/Plots/DYJetsM50_MassHist.pdf]]

** Calibration and energy scale uncertainties
  - Calibration process adjusts energy scale and resolution to match well-known resonances (Z boson, J/psi meson) in data and simulation,
 - Imperfect agreement due to subdetector complexities and nonlinear effects
*** How do analysis techniques respond to energy scale uncertainties ?
Our work will focus on the effects that energy scale uncertainties have, on a traditional fit-based analysis and a more modern Boosted Decision Tree-based analysis, using the generic diobject production process as the working example.
* Analysis techniqies
** Classification techniques
*In our case*:
- Signal: a resonant decay Y->xx
- Background: a non resonant process
*How to separate them?*
- Boosted Decision Trees
- Fit based analysis
* Analyis1: General Stuff
** Searches for \(Y \rightarrow XX\)
*** Search for heavy \(Y \rightarrow XX\)
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
Search for heavy \(Y \rightarrow XX\)
- Mass range from 100GeV up to 300GeV
*** Search for light \(Y \rightarrow XX\)
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
Search for light \(Y \rightarrow XX\)
- Mass range from 50GeV up to 70GeV
** The \(Y \rightarrow XX\) channel
  The specific characteristics(mass etc.) of each dataset  is different but the main idea is the same
  - Use a non resonant process for background --> Drell-Yan
  - Use a resonant process for signal --> $W\Phi \rightarrow ll$ 
  - Separate signal from background
  - Apply energy scale uncertainties to signal
  - Separate again
  - Compare the nominal case with the smeared cases
** Statistical interpretation of results
*Are the signal events we counted, statistically significant?*
 - We use the following metric:
\begin{equation}
\text{Significance} = \frac{Signal}{\sqrt{Background}}
\end{equation}

* Light mass search
** Search for light \(Y \rightarrow XX\)
We will study the following smearing cases:
*** Text
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- $0\%$(Nominal case)
- $5\%$
- $7\%$
- $10\%$
- $12\%$
The working mass range is quite small --> smearing has a significant effect real quick 
*** Figrue 
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=1,width=\textwidth]{/home/kpapad/UG_thesis/Thesis/Analysis/out/Plots/WPhiJets_M60M5080_Application_MassSpectrum.pdf}
\end{figure}
** Fit based approach: Fitting 
Then we proceed with the fits!
*** Figure 1
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=1,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M60M5080_FitALL.pdf}
\end{figure}

*** Figure 2
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=2,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M60M5080_FitALL.pdf}
\end{figure}

** Fit based approach: Fitting 
*** Figure 1
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=3,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M60M5080_FitALL.pdf}
\end{figure}

*** Figure 2
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=4,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M60M5080_FitALL.pdf}
\end{figure}

** Fit based approach: Fitting 
Any further smearing will make the signal indistiguishable!
\begin{figure}[h]
\centering
\includegraphics[page=5,width=0.55\textwidth]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M60M5080_FitALL.pdf}
\end{figure}

** Fit based approach: Signal from background separation  
Working in the nominal case, we find the region that yields the best significance, by scanning the ranges $m=\pm \frac{n}{2}\sigma\text{, }n=1, 2, 3, 4, 5, 6$ 
\begin{figure}[h]
\centering
\includegraphics[page=1,width=0.45\linewidth]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M60M5080_Significance0.pdf}
\end{figure}
** Fit based approach: Signal from background separation  
The region of interest that yields the best significance is the $\pm 1.5\sigma$. There are two ways to interpret this.
*** text
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- interpret $\sigma$ as the the spread of the nominal case --> fixed window
- interpret $\sigma$ as the the spread of each  cases --> adaptive window
*** figure  
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=3,width=0.8\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/src/WPhiJets_M60M5080_Significance.pdf}
\end{figure}
** BDT approach: Feature space 
*What features of the dataset are best for the classification task?*
\begin{figure}[h!]
\centering
\includegraphics[page=1,width=0.9\textwidth]{/home/kpapad/UG_thesis/Thesis/Analysis/out/Plots/WPhiJets_M60M5080DeltasVarsPlots.pdf}
\end{figure}
** BDT approach: Feature space
\begin{figure}[h!]
\centering
\includegraphics[page=2,width=0.9\textwidth]{/home/kpapad/UG_thesis/Thesis/Analysis/out/Plots/WPhiJets_M60M5080DeltasVarsPlots.pdf}
\end{figure}

** BDT approach: The model
*** Text
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- Trained with approximately 3K events
- To examine overfitting we compare the ratio of training events to testing for each bdt score  
*** Figure
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
  \begin{figure}[h!]
\centering
\includegraphics[page=5, width=\textwidth]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M60M5080DeltasPConf13BDTplot.pdf}
\end{figure}

** BDT approach: Application
Feed the application set to the BDT --> BDT plots
*** Figure 1
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=6,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M60M5080Deltas_Application13BDTplot.pdf}
\end{figure}
*** Figure 2
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=6,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M60M5080Deltas_Application_Smeared513BDTplot.pdf}
\end{figure}

** BDT approach: Application
*** Figure 1
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=6,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M60M5080Deltas_Application_Smeared713BDTplot.pdf}
\end{figure}
*** Figure 2
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=6,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M60M5080Deltas_Application_Smeared1013BDTplot.pdf}
\end{figure}

** BDT approach: Application
*** Figure 1
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=6,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M60M5080Deltas_Application_Smeared1213BDTplot.pdf}
\end{figure}

** BDT approach: Signal from background separation
*Where should we place the cut?*
*** Text
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- Same philosophy as in the fit based search
- We scan the bdt range to find the best region of interest
- Best cut --> BDT score = 0.96.
*** Figure
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}
\centering
\includegraphics[page=1,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/src/WPhiJets_M60M5080_Significance.pdf}
\end{figure}
** BDT approach: Signal from background separation
*** Text
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- The performance of the BDT remains invariant under energy scale uncertainties!
*** Figure
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}
\centering
\includegraphics[page=2,width=\textwidth]{/home/kpapad/UG_thesis/Thesis/Bdt/src/WPhiJets_M60M5080_Significance.pdf}
\end{figure}
** Synopsis
*** Light Y to XX
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- BDT performs better than the fit based
- Remains invariant under smearing
- Performance of the fit drops
*** Light Y to XX
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}
\centering
\includegraphics[page=4,width=\textwidth]{/home/kpapad/UG_thesis/Thesis/Bdt/src/WPhiJets_M60M5080_Significance.pdf}
\end{figure}

* Heavy mass search
** Search for heavy \(Y \rightarrow XX\) 
We will study the following smearing cases:\newline

*** Text
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
Medium to extreme cases 
- $0\%$(Nominal case)
- $5\%$
- $10\%$
- $15\%$
- $20\%$
\newline Plus some really extreme cases
- $30\%$
- $40\%$
- $50\%$
  
*** Figrue 
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=1,width=\textwidth]{/home/kpapad/UG_thesis/Thesis/Analysis/out/Plots/WPhiJets_M200M100300_Application_MassSpectrum.pdf}
\end{figure}

** Fit based approach: Signal Fitting 
Then we proceed and fit the signal
*** Figure 1
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=1,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M200M100300_FitALL.pdf}
\end{figure}

*** Figure 2
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=2,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M200M100300_FitALL.pdf}
\end{figure}

** Fit based approach: Signal Fitting 
*** Figure 1
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=3,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M200M100300_FitALL.pdf}
\end{figure}

*** Figure 2
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=4,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M200M100300_FitALL.pdf}
\end{figure}

** Fit based approach: Signal Fitting 
\begin{figure}[h]
\centering
\includegraphics[page=5,width=0.55\textwidth]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M200M100300_FitALL.pdf}
\end{figure}

** Fit based approach: Signal Fitting 
*** Figure 1
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=6,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M200M100300_FitALL.pdf}
\end{figure}

*** Figure 2
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=7,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M200M100300_FitALL.pdf}
\end{figure}

** Fit based approach: Signal Fitting 
\begin{figure}[h]
\centering
\includegraphics[page=8,width=0.55\textwidth]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M200M100300_FitALL.pdf}
\end{figure}

** Fit based approach: Signal from background separation  
Working in the nominal case, we scan the ranges $m=\pm \frac{n}{2}\sigma\text{, }n=1, 2, 3, 4, 5, 6$ 
\begin{figure}[h]
\centering
\includegraphics[page=1,width=0.45\textwidth]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M200M100300_Significance0.pdf}
\end{figure}
** Fit based approach: Signal from background separation  
The best significance is in the $\pm 1.5\sigma$ range. 
*** text
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- fixed window
- adaptive window
*** figure  
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=3,width=0.9\textwidth]{/home/kpapad/UG_thesis/Thesis/Bdt/src/WPhiJets_M200M100300_Significance.pdf}
\end{figure}
** BDT approach: Feature space 
We use the same feature space as with the light mass search
\begin{figure}[h!]
\centering
\includegraphics[page=1,width=0.9\textwidth]{/home/kpapad/UG_thesis/Thesis/Analysis/out/Plots/WPhiJets_M200M100300Deltas_varsplot.pdf}
\end{figure}
** BDT approach: Feature space
\begin{figure}[h!]
\centering
\includegraphics[page=2,width=0.9\textwidth]{/home/kpapad/UG_thesis/Thesis/Analysis/out/Plots/WPhiJets_M200M100300Deltas_varsplot.pdf}
\end{figure}

** BDT approach: The model
*** Text
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- Trained with approximately 3K events
- To examine overfitting we compare the ratio of training events to testing for each bdt score  
*** Figure
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
  \begin{figure}[h!]
\centering
\includegraphics[page=5, width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M200M100300DeltasPConf12BDTplot.pdf}
\end{figure}

** BDT approach: Application
Feed the application set to the BDT --> BDT plots
*** Figure 1
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=6,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M200M100300Deltas_Application12BDTplot.pdf}
\end{figure}
*** Figure 2
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=6,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M200M100300Deltas_Application_Smeared512BDTplot.pdf}
\end{figure}

** BDT approach: Application
*** Figure 1
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=6,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M200M100300Deltas_Application_Smeared1012BDTplot.pdf}
\end{figure}
*** Figure 2
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=6,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M200M100300Deltas_Application_Smeared1512BDTplot.pdf}
\end{figure}

** BDT approach: Application
*** Figure 1
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=6,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M200M100300Deltas_Application_Smeared2012BDTplot.pdf}
\end{figure}
*** Figure 2
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=6,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M200M100300Deltas_Application_Smeared3012BDTplot.pdf}
\end{figure}

** BDT approach: Application
*** Figure 1
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=6,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M200M100300Deltas_Application_Smeared4012BDTplot.pdf}
\end{figure}
*** Figure 2
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=6,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M200M100300Deltas_Application_Smeared5012BDTplot.pdf}
\end{figure}

** BDT approach: Signal from background separation
*Where should we place the cut?*
*** Text
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- We scan the whole bdt range to find the best region of interest
- Best cut --> BDT score = 0.98.
- This is rather tight, lets see what happens if we place a more relaxed cut at 0.86
*** Figure
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}
\centering
\includegraphics[page=1,width=\linewidth]{/home/kpapad/UG_thesis/Thesis/Bdt/src/WPhiJets_M200M100300_Significance.pdf}
\end{figure}
** BDT approach: Signal from background separation
*** Text
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- The performance of the more relaxed cut is not as good as the best cut
- The bdt model is rather robust
*** Figure
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}
\centering
\includegraphics[page=2,width=\textwidth]{/home/kpapad/UG_thesis/Thesis/Bdt/src/WPhiJets_M200M100300_Significance.pdf}
\end{figure}
** Synopsis
*** Heavy Y to XX
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- The perfomance of the BDT and Fit are comparable when smeaing is mild
- Fit perfomance drops dramatically 
- BDT is more robust

*** Heavy Y to XX
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}
\centering
\includegraphics[page=4,width=\textwidth]{/home/kpapad/UG_thesis/Thesis/Bdt/src/WPhiJets_M200M100300_Significance.pdf}
\end{figure}

* Results
** Results 
*** Light Y to XX
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- Light $Y \rightarrow XX$
\begin{figure}
\centering
\includegraphics[page=4,width=\textwidth]{/home/kpapad/UG_thesis/Thesis/Bdt/src/WPhiJets_M60M5080_Significance.pdf}
\end{figure}

*** Heavy Y to XX
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- Heavy $Y \rightarrow XX$
\begin{figure}
\centering
\includegraphics[page=4,width=\textwidth]{/home/kpapad/UG_thesis/Thesis/Bdt/src/WPhiJets_M200M100300_Significance.pdf}
\end{figure}

** Results 
Overall, the BDT is more robust as it learns features that do not get affected by energy scale uncertainties\newline

*So is the BDT better?*
- No: A more carefull event selection can improve the performance of the fit based analysis
- yes: In the presence of energy scale uncertainties, the fit based analysis reaches a "breaking point"
 
* Unused stuff
** Unused stuff
*Welcome to the backup slides!*

** The CMS Experiment overview
The CMS detector at the LHC
\begin{figure}[hb]
\centering
\includegraphics[width=0.7 \textwidth, ext=.png type=jpg]{/home/kpapad/UG_thesis/Thesis/Dissertation/src/figures/cms_detector.jpg}
\end{figure}

** Supervised Learning
*Supervised learning*:
 - The model is trained using training data
 - The trained model is tested using testing data
 - If we like the resulting model, we apply it!
   
*but what is this model?*
 - A function that given the input feautres x, it returns the probability x beeing class A
 - The goal of the training is to minimize the difference between the predicted output \(y_{i} \in [0, 1]\) and the real output \(\hat{y_{i}} = 0\text{ class B, or }\hat{y_{i}} = 1\text{ class A}\) 
** BDT 3: Signal from background separation
 Where should we place the cut in order to accpet most most of the  signal while rejecting most of background?
\begin{figure}[hb]
\centering
\includegraphics[page=2, width=0.85 \textwidth, ext=.png type=jpg]{/home/kpapad/UG_thesis/Thesis/Bdt/out/Plots/WPhiJets_M60M5080DeltasPConf12BDTplot.pdf}
\end{figure}
** BDT 1a: Boosted decision trees
In this study the model of choice is Boosted Decision Trees(BDT).
 - It classifies data using decision tree models
\begin{figure}[h]
\centering
\includegraphics[width=0.85 \textwidth, ext=.png type=png]{/home/kpapad/UG_thesis/Thesis/Dissertation/Presentation/figures/cart.png}
\end{figure}
** BDT 2b: Boosted Decision Trees
Usually only one tree is not power full enough --> Use  more trees in additive manner(Boosting)
\begin{figure}[h]
\centering
\includegraphics[width=0.85 \textwidth, ext=.png type=png]{/home/kpapad/UG_thesis/Thesis/Dissertation/Presentation/figures/twocart.png}
\end{figure}
** Fit based signal from background separation
Fit the mass spectrum ...
\begin{figure}[hb]
\centering
\includegraphics[page=2, width=0.5 \textwidth, ext=.png type=jpg]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M60M5080_SampleFitWArrows.pdf}
\end{figure}
** Fit based signal from background separation
... and decompose it to a background component ...
\begin{figure}[hb]
\centering
\includegraphics[page=3, width=0.5 \textwidth, ext=.png type=jpg]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M60M5080_SampleFitWArrows.pdf}
\end{figure}
** Fit based signal from background separation
... and a signal component
\begin{figure}[hb]
\centering
\includegraphics[page=4, width=0.5 \textwidth, ext=.png type=jpg]{/home/kpapad/UG_thesis/Thesis/Analysis/src/WPhiJets_M60M5080_SampleFitWArrows.pdf}
\end{figure}
** Fit based signal from background separation
Then we can count the signal and background events, in a region of interest \(I\):
\begin{align}
O &= \int_{I} observation(x) dx \\
B &= \int_{I} bkg(x) dx\\
S &= O - B
\end{align}

** Energy scale uncertainties
To smear the data by $x\%$,
- iterate over every signal event
- multiply each \(P_{T}\) by a number sampled from a Gaussian distribution of $\mu = 1$ and $\sigma = x/100$
** The \(Y \rightarrow XX\) channel: Background
- Drell-Yan process

** The \(Y \rightarrow XX\) channel: Signal
- W \(\Phi\) --> ll

** Search for light \(Y \rightarrow XX\) 
We will study the following smearing cases:
- $0\%$(Nominal case)
- $5\%$
- $7\%$
- $10\%$
- $12\%$
The working mass range is quite small --> smearing has a significant effect real quick 
** Fit based approach: Background Fitting light
*** Text
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- To simplify things a bit, we fit the background sepratelly
- The background shape is kept constant throughout the fits
- Shape: $\alpha + \beta x + \gamma x^2 + \delta x^3$
*** Figure
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=1,width=\textwidth]{/home/kpapad/UG_thesis/Thesis/Analysis/out/Plots/WPhiJets_M60M5080_Application_bkgonly_Fit.pdf}
\end{figure}

** Fit based approach: Background Fitting
*** Text
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
- The background shape is kept constant 
- Shape: $\alpha + \beta x^{-1/2} + \gamma x^{-1} + \delta x^{3/2}$
*** Figure
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
\begin{figure}[h]
\centering
\includegraphics[page=1,width=\textwidth]{/home/kpapad/UG_thesis/Thesis/Analysis/out/Plots/WPhiJets_M200M100300_Application_bkgFit.pdf}
\end{figure}

** Search for heavy \(Y \rightarrow XX\) 
We will study the following smearing cases:\newline
*** medium to extreme
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
Medium to extreme cases 
- $0\%$(Nominal case)
- $5\%$
- $10\%$
- $15\%$
- $20\%$
*** extreme extreme 
:PROPERTIES:
:BEAMER_col: 0.5
    :END:
Plus some really extreme cases
- $30\%$
- $40\%$
- $50\%$

